server:
    port: 8081

resilience4j.ratelimiter:
    configs:
        default:
            limitForPeriod: 5
            limitRefreshPeriod: 1s
            timeoutDuration: 0
    instances:
        serviceC:
            baseConfig: default